baseURL = 'https://kimjunil.github.io/'
languageCode = 'ko-kr'
title = 'My New Hugo Site'
theme = 'listed'
math = true

[frontmatter]
  date  = [":filename", ":default"]
  author = ""
  github = "kimjunil"
  facebook = ""
  og_image = ""
  sitename = "Liste"
  twitter = ""

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'dracula'
    tabWidth = 4